# Generated by Django 5.2.15 on 2026-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título opcional')),
                ('imagen', models.ImageField(upload_to='fotos_marco/', verbose_name='Archivo de imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
        ),
    ]
