# Generated by Django 5.2.15 on 2026-06-26 17:58

import django.utils.timezone
import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotomarco',
            name='fecha_visualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última vez mostrada'),
        ),
        migrations.AlterField(
            model_name='fotomarco',
            name='imagen',
            field=models.ImageField(upload_to=galeria.models.ruta_imagen_unica, verbose_name='Archivo de imagen'),
        ),
    ]
