# Generated by Django 5.2.15 on 2026-06-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotomarco_fecha_visualizacion_alter_fotomarco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotomarco',
            name='usuario',
            field=models.CharField(blank=True, default='Alguien', max_length=100, null=True, verbose_name='Subido por'),
        ),
    ]
