# Generated by Django 5.2.15 on 2026-07-03 15:33

import django.db.models.deletion
import galeria.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotomarco_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fotomarco',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
        migrations.AlterField(
            model_name='fotomarco',
            name='usuario',
            field=models.CharField(blank=True, default='Alguien', max_length=100, null=True, verbose_name='Subido por (nombre)'),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Galería')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(related_name='galerias', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios autorizados')),
            ],
        ),
        migrations.AddField(
            model_name='fotomarco',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='galeria.galeria', verbose_name='Galería'),
        ),
        migrations.CreateModel(
            name='MarcoDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del marco')),
                ('token_acceso', models.CharField(default=galeria.models.generar_token_dispositivo, max_length=64, unique=True, verbose_name='Token de acceso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('galeria_activa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcos_activos', to='galeria.galeria', verbose_name='Galería activa')),
                ('galerias_permitidas', models.ManyToManyField(related_name='marcos_autorizados', to='galeria.galeria', verbose_name='Galerías permitidas')),
            ],
        ),
    ]
