# Generated by Django 5.2.15 on 2026-07-03 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotomarco_usuario_creador_alter_fotomarco_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galerias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Dueño/Creador'),
        ),
        migrations.AddField(
            model_name='marcodispositivo',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración del código PIN'),
        ),
        migrations.AddField(
            model_name='marcodispositivo',
            name='codigo_vinculacion',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código PIN de vinculación'),
        ),
        migrations.AddField(
            model_name='marcodispositivo',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='fotomarco',
            name='usuario',
            field=models.CharField(blank=True, default='Alguien', max_length=100, null=True, verbose_name='Nombre de usuario (antiguo)'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Galería'),
        ),
        migrations.CreateModel(
            name='SolicitudUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='galeria.galeria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'galeria')},
            },
        ),
    ]
