# Generated by Django 5.2.15 on 2026-07-03 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_galeria_creador_marcodispositivo_codigo_expiracion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marcodispositivo',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcos_propios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario dueño/creador'),
        ),
    ]
